[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3 

[tool.djlint]
profile = "django"
ignore = "H031"
extension = "html"
indent = 2